init project
Linkurious/lke-plugin-hello-world pull request #1
Opened 2020-12-23 17:30 UTC by aminerhanemi

2020-12-28 09:25 UTC, yigitakbulut commented on hello-world.lke/buildcache/backend.tsbuildinfo
> +{
What is the purpose of this file? I think we can add this into .gitignore  as well.

2020-12-28 09:26 UTC, yigitakbulut commented on hello-world.lke/buildcache/public.tsbuildinfo
> +{
This is weird, it is in the .gitignore but still pushed.

2020-12-29 09:29 UTC, francescoinfante requested changes

2020-12-29 09:29 UTC, francescoinfante commented on .gitignore
> +hello-world.lke/buildcache/public.tsbuildinfo
just use *.lke, so the .gitignore will work also as boilerplate

2020-12-29 09:29 UTC, francescoinfante commented on hello-world.lke/backend/routeHandler.d.ts
> +import { PluginConfig, PluginRouteOptions } from '../@types/plugin';
we should not push the *.lke file to git. this is built code

2020-12-29 09:29 UTC, francescoinfante commented on src/public/index.ts
> +function main() {
when does this code get executed?

Instead I would just register a backend API that return hello world

2020-12-29 09:29 UTC, francescoinfante commented on tsconfig.json
> +    "include": [], // DO NOT DELETE: mandatory to keep even if empty
why?

2020-12-30 16:39 UTC, aminerhanemi commented on package.json
> +    "url": "git+https://github.com/Linkurious/lke-plugin-image-export.git"
hello-world and not image-export (same in all the file )

2020-12-30 16:51 UTC, merged